x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:v1.69.2
    container_name: homarr
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
      - DOCKER_HOSTNAMES=${DOCKER_HOSTNAMES}
      - DOCKER_PORTS=${DOCKER_PORTS}
    ports:
      - '7575:7575'