x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "3"
    
services:
  metube:
    image: ghcr.io/alexta69/metube:latest
    container_name: metube
    restart: unless-stopped
    logging: *default-logging
    user: "0:10000"
    ports:
      - "8081:8081"
    volumes:
      - ${DOWNLOADS}:/downloads
      - ${SMBSHARE}:/incoming
      - ${YTDL_OPTIONS_PRESETS_FILE}:/config/presets.json:ro
      - ${NOTIFY}:/notifications:ro
    environment:
      - DOWNLOAD_DIR=/downloads
      - YTDL_OPTIONS=${YTDL_OPTIONS}
      - YTDL_OPTIONS_PRESETS_FILE=/config/presets.json
      - OUTPUT_TEMPLATE=${OUTPUT_TEMPLATE}
      - TZ=${TIMEZONE}
      - LOGLEVEL=${LOGLEVEL}
      - DEFAULT_THEME=${DEFAULT_THEME}
      - MAX_CONCURRENT_DOWNLOADS=1
      - NTFY_TOPIC=${NTFY_TOPIC}
      
volumes:
  metube_state: